name: CI/CD for COP-DM web app

on: 
  push:
    branches:
    - master

env:
  BUCKET_NAME : “copenhagen-university-trial-data-intermediate”
  AWS_REGION : "eu-central-1"

# Permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::372814917336:role/cop-dm-cicd-role"
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync SHI web app files to the S3 bucket with the AWS CLI
        run: |
          aws s3 sync "./Cloud-deployment" s3://copenhagen-university-trial-data-intermediate --follow-symlinks --delete
